server:
  port: 8080
externaldata:
  user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:11.0) Gecko/20100101 Firefox/11.0
  referrer: https://www.google.com
logging:
  level:
    org:
      hibernate:
        type: info
      springframework:
        test: 
          web: 
            servlet:
              MockMvc: DEBUG

spring:
  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  datasource:
    username: zero
    password: one
    url: jdbc:postgresql://localhost:5432/search_engine
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changeset/db.changelog-master.xml